// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNwoyaznout9lBGce43cIV0-GWyJ5Cs6M',
    appId: '1:641472217128:web:aeb4a2159d22eb29e7351d',
    messagingSenderId: '641472217128',
    projectId: 'flutter-prep-cc59f',
    authDomain: 'flutter-prep-cc59f.firebaseapp.com',
    databaseURL: 'https://flutter-prep-cc59f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-cc59f.appspot.com',
    measurementId: 'G-0TTPFVWK1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-MZ88Ww4B_brUbFlty7K0Hjuev6Nhlg',
    appId: '1:641472217128:android:3e1dd45077f5eebae7351d',
    messagingSenderId: '641472217128',
    projectId: 'flutter-prep-cc59f',
    databaseURL: 'https://flutter-prep-cc59f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-cc59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6ps09trdRZKzcLx8jzZGKVUG5Xw25gU',
    appId: '1:641472217128:ios:f4a775d371ef35f8e7351d',
    messagingSenderId: '641472217128',
    projectId: 'flutter-prep-cc59f',
    databaseURL: 'https://flutter-prep-cc59f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-cc59f.appspot.com',
    iosBundleId: 'com.example.vigenasia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6ps09trdRZKzcLx8jzZGKVUG5Xw25gU',
    appId: '1:641472217128:ios:8852d19911a94f87e7351d',
    messagingSenderId: '641472217128',
    projectId: 'flutter-prep-cc59f',
    databaseURL: 'https://flutter-prep-cc59f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-cc59f.appspot.com',
    iosBundleId: 'com.example.vigenasia.RunnerTests',
  );
}
